//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalTest.BusinessLogic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCSV> tblCSVs { get; set; }
        public virtual DbSet<tblCSVPaymentDetail> tblCSVPaymentDetails { get; set; }
        public virtual DbSet<tblExcel> tblExcels { get; set; }
        public virtual DbSet<tblXMLPaymentDetail> tblXMLPaymentDetails { get; set; }
    }
}
